In [74]:
from tensorflow.keras.preprocessing.text import one_hot

In [75]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [76]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [77]:
voc_size=10000

In [78]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[877, 6813, 1259, 2251], [877, 6813, 1259, 3578], [877, 1396, 1259, 9815], [6380, 9451, 9428, 4355, 6588], [6380, 9451, 9428, 4355, 8505], [8471, 877, 2132, 1259, 2103], [9482, 7901, 9772, 4355]]


In [79]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [80]:
import numpy as np

In [81]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  877 6813 1259 2251]
 [   0    0    0    0  877 6813 1259 3578]
 [   0    0    0    0  877 1396 1259 9815]
 [   0    0    0 6380 9451 9428 4355 6588]
 [   0    0    0 6380 9451 9428 4355 8505]
 [   0    0    0 8471  877 2132 1259 2103]
 [   0    0    0    0 9482 7901 9772 4355]]


In [82]:
dim=10

In [90]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [91]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step
[[[ 0.03343104  0.02337222  0.0284237  -0.00563685  0.00998754
    0.0137453  -0.0267024  -0.04366409  0.03927005  0.01822534]
  [ 0.03343104  0.02337222  0.0284237  -0.00563685  0.00998754
    0.0137453  -0.0267024  -0.04366409  0.03927005  0.01822534]
  [ 0.03343104  0.02337222  0.0284237  -0.00563685  0.00998754
    0.0137453  -0.0267024  -0.04366409  0.03927005  0.01822534]
  [ 0.03343104  0.02337222  0.0284237  -0.00563685  0.00998754
    0.0137453  -0.0267024  -0.04366409  0.03927005  0.01822534]
  [-0.01593586  0.04761383 -0.02395995 -0.03417215  0.03377643
   -0.01811571  0.04174266 -0.0463189  -0.04003357 -0.03849002]
  [-0.04376401  0.04014896 -0.04989564 -0.01534367 -0.02541301
   -0.03824576  0.00797262 -0.01553409  0.04299981 -0.02702818]
  [-0.02279327  0.02349659 -0.03799624 -0.03709067 -0.01548567
    0.04952488  0.02347037 -0.04949305 -0.04205285  0.04932101]
  [-0.0449705  -0.00453638  0.00647337  0.00550427  0.03716994
    0.025

In [92]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape          ┃      Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)       │ (7, 8, 10)            │      100,000 │
└───────────────────────────────┴───────────────────────┴──────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [93]:
embedded_docs[0]

array([   0,    0,    0,    0,  877, 6813, 1259, 2251])

In [94]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[ 0.03343104  0.02337222  0.0284237  -0.00563685  0.00998754  0.0137453
  -0.0267024  -0.04366409  0.03927005  0.01822534]
 [ 0.03343104  0.02337222  0.0284237  -0.00563685  0.00998754  0.0137453
  -0.0267024  -0.04366409  0.03927005  0.01822534]
 [ 0.03343104  0.02337222  0.0284237  -0.00563685  0.00998754  0.0137453
  -0.0267024  -0.04366409  0.03927005  0.01822534]
 [ 0.03343104  0.02337222  0.0284237  -0.00563685  0.00998754  0.0137453
  -0.0267024  -0.04366409  0.03927005  0.01822534]
 [-0.01593586  0.04761383 -0.02395995 -0.03417215  0.03377643 -0.01811571
   0.04174266 -0.0463189  -0.04003357 -0.03849002]
 [-0.04376401  0.04014896 -0.04989564 -0.01534367 -0.02541301 -0.03824576
   0.00797262 -0.01553409  0.04299981 -0.02702818]
 [-0.02279327  0.02349659 -0.03799624 -0.03709067 -0.01548567  0.04952488
   0.02347037 -0.04949305 -0.04205285  0.04932101]
 [-0.0449705  -0.00453638  0.00647337  0.00550427  0.03716994  0.02546616
  -0.03715786  0.